name: 55 DL Full
on: workflow_dispatch
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2

   - name: Login to Azure
     uses: azure/login@v1.1
     with:
       creds: ${{ secrets.AZURELOGINCREDS }}

   - name: Create Resource Group
     uses: azure/arm-deploy@v1
     with:
       scope: subscription
       subscriptionId: ${{ secrets.SUBSCRIPTIONID }}
       region: eastus2
       template: ./templates/resourcegroup.json
       parameters:
         ResourceGroupName=${{ secrets.RESOURCEGROUPNAME }}

   - name: Create Data Lake
     uses: azure/arm-deploy@v1
     with:
       subscriptionId: ${{ secrets.SUBSCRIPTIONID }}
       resourceGroupName: ${{ secrets.RESOURCEGROUPNAME }}
       template: ./templates/datalake.json

   - name: Create Data Lake Container
     uses: azure/arm-deploy@v1
     with:
       subscriptionId: ${{ secrets.SUBSCRIPTIONID }}
       resourceGroupName: ${{ secrets.RESOURCEGROUPNAME }}
       template: ./templates/datalakecontainer.json

   - name: Create Role Assignment
     uses: azure/arm-deploy@v1
     with:
       subscriptionId: ${{ secrets.SUBSCRIPTIONID }}
       resourceGroupName: ${{ secrets.RESOURCEGROUPNAME }}
       template: ./templates/datalakeroleassignment.json



   - name: TESTER
     shell: pwsh
     run: |
       az storage fs directory create -n blubb -f 809rgdlfs --account-name 809rgdl --auth-mode login