name: 23 Data Lake Directory Create
on: workflow_dispatch
#on: [push]

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2

   - name: Login to Azure
     uses: azure/login@v1
     with:
       creds: ${{ secrets.AZURELOGINCREDS }}
       enable-AzPSSession: true


   - name: Create Directory
     uses: Azure/powershell@v1
     with:
        inlineScript: ./scripts/DL_createDirectory.ps1
        azPSVersion: "latest"