name: 66 Data Lake Directory ACL
on: workflow_dispatch
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2

   - name: Login to Azure
     uses: azure/login@v1.1
     with:
       creds: ${{ secrets.AZURELOGINCREDS }}



   - name: Update Directory
     shell: pwsh
     run: |
       $ctx = New-AzStorageContext -StorageAccountName '809rgdl' -UseConnectedAccount
       $filesystemName = "809rgdlfs"
       $dirname = "blubb/"
       $userID = "24f06d41-b39b-4aa9-97bb-076201bd8ba9";
       $permission = "rw-";
       $acl = Set-AzDataLakeGen2ItemAclObject -AccessControlType user -EntityId $userID -Permission $permission
       Update-AzDataLakeGen2AclRecursive -Context $ctx -FileSystem $filesystemName -Path $dirname -Acl $acl
