name: 500 KD Part A - create AD Groups, add Member
#on: workflow_dispatch
on: [push]

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3

   - name: Login to Azure
     uses: azure/login@v1
     with:
       creds: ${{ secrets.AZURELOGINCREDS }}
       enable-AzPSSession: true


   - name: Create AD Group - Producer
     uses: Azure/powershell@v1
     with:
        inlineScript: ./scripts/KD_createAdGroups.ps1 -group 'Producer001'
        azPSVersion: "latest"

    - name: Add Member to AD Group - Producer
     uses: Azure/powershell@v1
     with:
        inlineScript: ./scripts/KD_addMemberToGroup.ps1 -group 'Producer001' -user 'batman@diginata.com'
        azPSVersion: "latest"


   - name: Create AD Group - Consumer
     uses: Azure/powershell@v1
     with:
        inlineScript: ./scripts/KD_createAdGroups.ps1 -group 'Consumer001'
        azPSVersion: "latest"

    - name: Add Member to AD Group - Consumer
     uses: Azure/powershell@v1
     with:
        inlineScript: ./scripts/KD_addMemberToGroup.ps1 -group 'Consumer001' -user 'superman@diginata.com'
        azPSVersion: "latest"


   - name: Create Directory (Folder)
     uses: Azure/powershell@v1
     with:
        inlineScript: ./scripts/DL_createDirectory.ps1
        azPSVersion: "latest"


   - name: Update Directory ACL
     uses: Azure/powershell@v1
     with:
        inlineScript: ./scripts/DL_setACLpermissions.ps1
        azPSVersion: "latest"
  

   - name: Update Container ACL
     uses: Azure/powershell@v1
     with:
        inlineScript: ./scripts/DL_setACLpermissions.ps1
        azPSVersion: "latest"