name: 500 KD Part A - create AD Groups, add Member
#on: workflow_dispatch
on: [push]

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3

   - name: Login to Azure
     uses: azure/login@v1
     with:
       creds: ${{ secrets.AZURELOGINCREDS }}
       enable-AzPSSession: true


   - name: Create AD Group
     uses: Azure/powershell@v1
     with:
        inlineScript: ./scripts/KD_createAdGroups.ps1 -group 'test56'
        azPSVersion: "latest"

 
   - name: Add Member to AD Group
     uses: Azure/powershell@v1
     with:
        inlineScript: ./scripts/KD_addMemberToGroup.ps1 -user 'batman@diginata.com' -group 'test56'
        azPSVersion: "latest"