name: 500 KD - create Folder, Groups & set Permissions
#on: workflow_dispatch
on: push

env:
 PRODUCER: Producer007
 CONSUMER: Consumer007
 FOLDER: test007
 CONTAINER: 1117rgdlfs
 RESOURCE: 1117rgdl
 PERMISSION_FOLDER_PRODUCER: rw-
 PERMISSION_FOLDER_CONSUMER: rwx
 PERMISSION_CONTAINER: Storage Blob Data Contributor

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3

   - name: Login to Azure
     uses: azure/login@v1
     with:
       creds: ${{ secrets.AZURELOGINCREDS }}
       enable-AzPSSession: true

   - name: Create AD Group - Producer
     uses: Azure/powershell@v1
     with:
       inlineScript: ./scripts/KD_Ops_createGroup.ps1 -group ${{ env.PRODUCER }}
       azPSVersion: "latest"

   - name: Add Member to AD Group - Producer
     uses: Azure/powershell@v1
     with:
       inlineScript: ./scripts/KD_Ops_addUserToGroup.ps1 -group ${{ env.PRODUCER }} -user 'batman@diginata.com'
       azPSVersion: "latest"

   - name: Create AD Group - Consumer
     uses: Azure/powershell@v1
     with:
       inlineScript: ./scripts/KD_Ops_createGroup.ps1 -group ${{ env.CONSUMER }}
       azPSVersion: "latest"

   - name: Add Member to AD Group - Consumer
     uses: Azure/powershell@v1
     with:
       inlineScript: ./scripts/KD_Ops_addUserToGroup.ps1 -group ${{ env.CONSUMER }} -user 'superman@diginata.com'
       azPSVersion: "latest"

   - name: Create Directory (Folder)
     uses: Azure/powershell@v1
     with:
       inlineScript: ./scripts/KD_Ops_createDirectory.ps1 -resource ${{ env.RESOURCE }} -container ${{ env.CONTAINER }} -folder ${{ env.FOLDER }}
       azPSVersion: "latest"

   - name: Update Directory ACL - Consumer
     uses: Azure/powershell@v1
     with:
       inlineScript: ./scripts/KD_Ops_SetACL.ps1 -resource ${{ env.RESOURCE }} -container ${{ env.CONTAINER }} -folder ${{ env.FOLDER }} -group ${{ env.CONSUMER }} -permission ${{ env.PERMISSION_FOLDER_CONSUMER}}
       azPSVersion: "latest"

   - name: Update Directory ACL - Producer
     uses: Azure/powershell@v1
     with:
       inlineScript: ./scripts/KD_Ops_SetACL.ps1 -resource ${{ env.RESOURCE }} -container ${{ env.CONTAINER }} -folder ${{ env.FOLDER }} -group ${{ env.PRODUCER }} -permission ${{ env.PERMISSION_FOLDER_PRODUCER}}
       azPSVersion: "latest"

   - name: Update Container Permission - Consumer
     uses: Azure/powershell@v1
     with:
       inlineScript: ./scripts/KD_Ops_SetContainerPermission.ps1 -resource ${{ env.RESOURCE }} -container ${{ env.CONTAINER }} -group ${{ env.CONSUMER }} -role ${{ env.PERMISSION_CONTAINER }} -resourcegroup ${{ secrets.RESOURCEGROUPNAME }} -subscription ${{ secrets.SUBSCRIPTIONID }}
       azPSVersion: "latest"

   - name: Update Container Permission - Producer
     uses: Azure/powershell@v1
     with:
       inlineScript: ./scripts/KD_Ops_SetContainerPermission.ps1 -resource ${{ env.RESOURCE }} -container ${{ env.CONTAINER }} -group ${{ env.PRODUCER }} -role 'Storage Blob Data Contributor' -resourcegroup ${{ secrets.RESOURCEGROUPNAME }} -subscription ${{ secrets.SUBSCRIPTIONID }}
       azPSVersion: "latest"