name: 500 KD - create Folder, Groups & set Permissions
on: workflow_dispatch
#on: push

env:
 PRODUCER: Producer005

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3

   - name: Login to Azure
     uses: azure/login@v1
     with:
       creds: ${{ secrets.AZURELOGINCREDS }}
       enable-AzPSSession: true

   - name: Create AD Group - Producer
     uses: Azure/powershell@v1
     with:
       inlineScript: ./scripts/KD_Ops_createGroup.ps1 -group $PRODUCER
       azPSVersion: "latest"

   - name: Add Member to AD Group - Producer
     uses: Azure/powershell@v1
     with:
       inlineScript: ./scripts/KD_Ops_addUserToGroup.ps1 -group 'Producer004' -user 'batman@diginata.com'
       azPSVersion: "latest"

   - name: Create AD Group - Consumer
     uses: Azure/powershell@v1
     with:
       inlineScript: ./scripts/KD_Ops_createGroup.ps1 -group 'Consumer004'
       azPSVersion: "latest"

   - name: Add Member to AD Group - Consumer
     uses: Azure/powershell@v1
     with:
       inlineScript: ./scripts/KD_Ops_addUserToGroup.ps1 -group 'Consumer004' -user 'superman@diginata.com'
       azPSVersion: "latest"

   - name: Create Directory (Folder)
     uses: Azure/powershell@v1
     with:
       inlineScript: ./scripts/KD_Ops_createDirectory.ps1 -folder 'test004' -container '1117rgdlfs' -resource '1117rgdl'
       azPSVersion: "latest"

   - name: Update Directory ACL - Consumer
     uses: Azure/powershell@v1
     with:
       inlineScript: ./scripts/KD_Ops_SetACL.ps1 -resource '1117rgdl' -container '1117rgdlfs' -folder 'test004' -group 'Consumer004' -permission 'rw-'
       azPSVersion: "latest"

   - name: Update Directory ACL - Producer
     uses: Azure/powershell@v1
     with:
       inlineScript: ./scripts/KD_Ops_SetACL.ps1 -resource '1117rgdl' -container '1117rgdlfs' -folder 'test004' -group 'Producer004' -permission 'rwx'
       azPSVersion: "latest"

   - name: Update Container Permission - Consumer
     uses: Azure/powershell@v1
     with:
       inlineScript: ./scripts/KD_Ops_SetContainerPermission.ps1 -resource '1117rgdl' -container '1117rgdlfs' -group 'Consumer004' -role 'Storage Blob Data Contributor' -resourcegroup ${{ secrets.RESOURCEGROUPNAME }} -subscription ${{ secrets.SUBSCRIPTIONID }}
       azPSVersion: "latest"

   - name: Update Container Permission - Producer
     uses: Azure/powershell@v1
     with:
       inlineScript: ./scripts/KD_Ops_SetContainerPermission.ps1 -resource '1117rgdl' -container '1117rgdlfs' -group 'Producer004' -role 'Storage Blob Data Contributor' -resourcegroup ${{ secrets.RESOURCEGROUPNAME }} -subscription ${{ secrets.SUBSCRIPTIONID }}
       azPSVersion: "latest"