name: 500 KD - set ACL only
#on: workflow_dispatch
on: push

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3

   - name: Login to Azure
     uses: azure/login@v1.1
     with:
       creds: ${{ secrets.AZURELOGINCREDS }}

   - name: Update Directory ACL - Producer
     uses: Azure/powershell@v1
     with:
       inlineScript: ./scripts/KD_Ops_SetACL2.ps1
       azPSVersion: "latest"

   - name: Update Directory ACL - Consumer
     uses: Azure/powershell@v1
     with:
       inlineScript: ./scripts/KD_Ops_SetACL.ps1 -resource '1117rgdl' -container '1117rgdlfs' -folder 'test001' -group 'Consumer001' -permission 'rw-'
       azPSVersion: "latest"

   - name: Update Container Permission
     uses: Azure/powershell@v1
     with:
       inlineScript: ./scripts/KD_Ops_SetContainerPermission.ps1 -group 'Consumer001' -role 'Storage Blob Data Contributor'
       azPSVersion: "latest"