name: 200 KD Part A - RG, DL, Container
on: workflow_dispatch
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2

   - name: Login to Azure
     uses: azure/login@v1.1
     with:
       creds: ${{ secrets.AZURELOGINCREDS }}

   - name: Create Resource Group
     uses: azure/arm-deploy@v1
     with:
       scope: subscription
       subscriptionId: ${{ secrets.SUBSCRIPTIONID }}
       region: eastus2
       template: ./templates/resourcegroup.json
       parameters:
         ResourceGroupName=${{ secrets.RESOURCEGROUPNAME }}

   - name: Create Data Lake
     uses: azure/arm-deploy@v1
     with:
       subscriptionId: ${{ secrets.SUBSCRIPTIONID }}
       resourceGroupName: ${{ secrets.RESOURCEGROUPNAME }}
       template: ./templates/datalake.json

   - name: Create Data Lake Container
     uses: azure/arm-deploy@v1
     with:
       subscriptionId: ${{ secrets.SUBSCRIPTIONID }}
       resourceGroupName: ${{ secrets.RESOURCEGROUPNAME }}
       template: ./templates/datalakecontainer.json


    - name: Create Role Assignment, Storage Blob Data Contributor
     uses: azure/arm-deploy@v1
     with:
       subscriptionId: ${{ secrets.SUBSCRIPTIONID }}
       resourceGroupName: ${{ secrets.RESOURCEGROUPNAME }}
       template: ./templates/KD_A_datalakeroleassignment.json